server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zp245491220/springConfig.git
          clone-on-start: true
          username: ########
          password: ########
      discovery:
        enabled: true
        service-id: config-server
  application:
    name: config-server
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health